name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

env:
  default-python-version: 3.8

jobs:

  lint:

    name: Project Quality Analysis
    runs-on: ubuntu-latest
    if: github.event.action == 'request-integration' && github.event.client_payload.repository == 'jackdewinter/pymarkdown'

    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Python ${{ env.default-python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ env.default-python-version }}

      - name: Install PipEnv
        run: |
          pip install pipenv==2022.1.8

      - name: Sync With Repository
        run: |
          pipenv lock
          pipenv sync

      - name: Execute Black
        run: |
          pipenv run black .

      - name: Execute ISort
        run: |
          pipenv run isort .

      - name: Execute Flake8
        run: pipenv run flake8 --exclude dist,build

      - name: Execute PyLint
        run: pipenv run pylint ${{github.workspace}}/test

      - name: Execute MyPy
        run: pipenv run mypy --strict test

      # - name: Execute PyMarkdown on Current Docs
      #   run: pipenv run python ${{github.workspace}}/main.py --config ${{github.workspace}}/clean.json scan ${{github.workspace}} ${{github.workspace}}/docs

  pre-commit-tests:

    name: Pre-Commit Tests
    strategy:
      matrix:
        # python: ["3.8", "3.9", "3.10"]
        python: ["3.8"]
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    if: github.event.action == 'request-integration' && github.event.client_payload.repository == 'jackdewinter/pymarkdown'

    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install PipEnv
        run: |
          pip install pipenv==2022.1.8

      - name: Sync With Repository
        run: |
          pipenv lock
          pipenv sync
          pipenv uninstall pytest-html

      - name: Get Hash From Event Information
        if: github.event.action == 'request-integration' && github.event.client_payload.repository == 'jackdewinter/pymarkdown'
        run: |
          echo "REMOTE_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV

      - name: Execute Tests
        run: |
          echo "Running tests with hash '${{ env.REMOTE_SHA }}'."
          pipenv run pytest

  install-tests:

    name: Install Package Tests
    runs-on: ubuntu-latest
    # if: github.event.action == 'request-integration' && github.event.client_payload.repository == 'jackdewinter/pymarkdown'

    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Get Hash From Event Information
        run: |
          # echo "REMOTE_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
          echo "REMOTE_SHA=108727f2c08db98043b5e0bc5136b7daf54beb59" >> $GITHUB_ENV

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          github_token: ${{ secrets.INTER_PROJECT_ACCESS_TOKEN }}
          repo: jackdewinter/pymarkdown
          commit: ${{ env.REMOTE_SHA }}
          workflow_conclusion: success
          path: ${{github.workspace}}/packages

      - name: Execute Tests
        run: |
          echo "Running tests with hash '${{ env.REMOTE_SHA }}'."
          ls -laR ${{github.workspace}}/packages
